### ISSUE TITLE
DEV - Maradék Todo

### ISSUE THREAD

**Issue by Harii75** [Harii75/startship-equations#32]
- [x] - Tesztesetek bővítése
- [x] - Story(XML) Balance
- [x] - lvlup reward
- [x] - npc scenario
- [x] - buff degradation
- [x] - enemy random attack (0-enemy.damage)

- [x] - Éles környezet; teszt fegyverek kivétele, player stat reset

**Comment by Harii75** [comment]
Ezek az utolsó darabok, ezután késznek tekinthető.
